name: Daily Email Reminder

on:
  schedule:
    # Run every day at 6:00 AM Israel time (UTC+3, so 3:00 AM UTC)
    - cron: '0 3 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-email-reminders:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code (force fresh)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true
    
    - name: Verify latest commit
      run: |
        echo "Current commit: $(git rev-parse HEAD)"
        echo "Latest commit on master: $(git rev-parse origin/master)"
        git log --oneline -5
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Verify script content
      run: |
        echo "Checking if small fixed wing code exists in script..."
        if grep -q "Small fixed wing license expires" scripts/email-reminder.js; then
          echo "✅ Small fixed wing code found in script"
        else
          echo "❌ Small fixed wing code NOT found in script"
        fi
        echo "Script last modified: $(stat -c %y scripts/email-reminder.js)"
    
    - name: Run email reminder script
      run: node scripts/email-reminder.js
      env:
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
        EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
        EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
        EMAILJS_PRIVATE_KEY: ${{ secrets.EMAILJS_PRIVATE_KEY }}
